### ISSUE TITLE
when will the code be released?

### ISSUE THREAD

**Issue by vitamin520** [YCHang686/SCS-Co#1]
Hi, when will the code be released? I am very interested in the dynamic color transfer part of your work.

**Comment by YCHang686** [comment]
Hi, really appreciate your interest in our work! I have other work to do, but I'm also preparing this code. Please be a little bit more patient. Thank you!

**Comment by voldemortX** [comment]
@YCHang686 Hi! I don't mean to rush you. But what is the status of code release now? Is there a timeline to expect?
